import os
import smtplib
from email.message import EmailMessage
from FireStoreDB import FireStoreDB
import schedule
import time

db = FireStoreDB()
client = db.connect()
# Email configuration
SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587
passwordFile = open(os.path.join(os.path.dirname(__file__), 'files', 'emailInfo.txt'), 'r')
USERNAME = passwordFile.readline().strip()
# app password generated by google
PASSWORD = passwordFile.readline().strip()


# Create morning reminder message
def create_morning_email(to_email):
    msg = EmailMessage()
    msg['Subject'] = 'A great way to start the day!'
    msg['From'] = USERNAME
    msg['To'] = to_email
    msg.set_content('''
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Morning Reminder</title>
        </head>
        <body style="background-color: #000000; color: #ffffff; font-family: Arial, sans-serif; text-align: center; padding: 20px;">
            <div style="max-width: 600px; margin: 0 auto;">
                <h1 style="color: #00a6ff; font-size: 55px; margin-bottom: 5px;">OpenHand</h1>
                <p style="font-size: 16px; margin-top: 0; margin-bottom: 40px;">Empowering Communication for All</p>
                
                <p style="font-size: 24px;">Morning reminder to come study with Handy!</p>
                
                <div style="border: 3px solid #00a6ff; border-radius: 40px; padding: 20px; margin: 40px 0;">
                    <p style="font-size: 30px;">A new sign learned...</p>
                    <img src="https://d15k2d11r6t6rl.cloudfront.net/pub/bfra/2sfzaa6x/v24/k05/3ni/ScholarHandy.jpg" alt="Scholar Handy" style="width: 250px; height: auto; border-radius: 10px;">
                    <p style="font-size: 30px;">Could be a new friend made!</p>
                </div>
                
                <a href="http://localhost:5173/" style="background-color: #00a6ff; color: #ffffff; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-size: 18px; display: inline-block;">Begin lesson</a>
            </div>
        </body>
        </html>''', subtype='html')
    return msg

def send_morning_reminder_email():
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(USERNAME, PASSWORD)

        users_ref = client.collection('users').stream()
        for doc in users_ref:
            user_data = doc.to_dict()
            if user_data.get('mornEmail') == True:
                try:
                    msg = create_morning_email(user_data.get('email'))
                    server.send_message(msg)
                    print('Email sent successfully!')
                except Exception as e:
                    print(f'Error: {e}')
    except Exception as e:
        print(f'Error: {e}')
    finally:
        server.quit()



schedule.every().day.at('09:25:00').do(send_morning_reminder_email)

KeepRunning = True
while KeepRunning:
    schedule.run_pending()
    time.sleep(1)

'''
print(f"Attempting to send email from {USERNAME}...")
try:
    server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
    server.starttls()
    try:
        server.login(USERNAME, PASSWORD)
    except smtplib.SMTPAuthenticationError:
        print("ERROR: Authentication failed. Please ensure you are using a specific App Password, not your regular Gmail password.")
    
    msg = create_morning_email('sperlingjr.cs@gmail.com')
    server.send_message(msg)
    print(f'Email sent successfully to sperlingjr.cs@gmail.com')
    server.quit()
except Exception as e:
    print(f'Error sending email details: {e}')
    '''