import { type ClassCardProps } from "../../components/cards/ClassCard";
export const classesData: ClassCardProps[] = [
  {
    id: "numbers",
    title: "Level 1",
    description: "25 questions that test your number knowledge.",
    questions: 25,
    level: "beginner",
    // imageSrc: "/images/classes/numbers.png",
  },
  {
    id: "letters",
    title: "Level 2",
    description: "40 questions that test your letter knowledge.",
    questions: 40,
    level: "beginner",
  },
  {
    id: "numbers-letters",
    title: "Level 3",
    description: "30 questions that mix numbers and letters.",
    questions: 30,
    level: "beginner",
  },
  {
    id: "common-words",
    title: "Level 4",
    description: "25 questions that test your word knowledge.",
    questions: 25,
    level: "intermediate",
  },
  {
    id: "letters-words",
    title: "Level 5",
    description: "40 questions that test your letter knowledge.",
    questions: 40,
    level: "intermediate",
  },
  {
    id: "numbers-words",
    title: "Level 6",
    description: "30 questions that mix numbers with words.",
    questions: 30,
    level: "intermediate",
  },
  {
    id: "phrases",
    title: "Level 7",
    description: "25 questions that test your phrase knowledge.",
    questions: 25,
    level: "advanced",
    // imageSrc: "/images/classes/phrases.png",
  },
  {
    id: "Esteban",
    title: "Level 8",
    description: "25 questions that test your phrase knowledge.",
    questions: 25,
    level: "advanced",
    // imageSrc: "/images/classes/phrases.png",
  },
  {
    id: "Jhon",
    title: "Level 9",
    description: "25 questions that test your phrase knowledge.",
    questions: 25,
    level: "advanced",
    // imageSrc: "/images/classes/phrases.png",
  },
  {
    id: "Esteban",
    title: "Level 10",
    description: "25 questions that test your phrase knowledge.",
    questions: 25,
    level: "advanced",
    // imageSrc: "/images/classes/phrases.png",
  },
  {
    id: "High",
    title: "Level 11",
    description: "25 questions that test your phrase knowledge.",
    questions: 25,
    level: "advanced",
    // imageSrc: "/images/classes/phrases.png",
  },
  {
    id: "Hello",
    title: "Level 12",
    description: "25 questions that test your phrase knowledge.",
    questions: 25,
    level: "advanced",
    // imageSrc: "/images/classes/phrases.png",
  },
  {
    id: "Mike",
    title: "Level 13",
    description: "25 questions that test your phrase knowledge.",
    questions: 25,
    level: "advanced",
    // imageSrc: "/images/classes/phrases.png",
  },
];
