export type Level = "beginner" | "intermediate" | "advanced";

export type WeeklySeries = number[]; // 7 numbers, F..T (Fri->Thu for the graph labels below)

export type User = {
  id: string;
  firstName: string;
  lastName: string;
  nickname: string;         // display name (big)
  username: string;         // handle, shown as @username
  email: string;
  level: Level;
  xp: number;
  dob: string;              // ISO date "YYYY-MM-DD"
  joinDate: string;         // ISO date "YYYY-MM-DD"
  dailyStreak: number;
  lessonsAvgGrade: number;  // 0..100
  followers: number;
  following: number;
  weeklyThis: WeeklySeries; // 7 pts (lessons per day) for "This week"
  weeklyLast: WeeklySeries; // 7 pts for "Last week" (comparison)
  avatarSrc?: string;
};
  export const usersData: User[] = [
  {
    id: "user1",
    firstName: "Lena",
    lastName: "Morales",
    nickname: "Lena",
    username: "lenam",
    email: "lena.morales@example.com",
    level: "beginner",
    xp: 1240,
    lessonsAvgGrade: 88,
    dob: "1999-03-17",
    joinDate: "2019-08-12",
    followers: 15,
    following: 15,
    dailyStreak: 5,
    weeklyThis: [3, 2, 6, 1, 2, 4, 0],
    weeklyLast: [8, 3, 2, 0, 2, 6, 1],
    avatarSrc: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: "user2",
    firstName: "Devon",
    lastName: "Nguyen",
    nickname: "Dev",
    username: "dev_ng",
    email: "devon.nguyen@example.com",
    level: "intermediate",
    xp: 3560,
    lessonsAvgGrade: 92,
    dob: "1995-11-02",
    joinDate: "2018-05-01",
    followers: 47,
    following: 31,
    dailyStreak: 14,
    weeklyThis: [0, 1, 4, 5, 2, 7, 0],
    weeklyLast: [2, 0, 3, 4, 1, 2, 0],
    avatarSrc: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: "user3",
    firstName: "Priya",
    lastName: "Rao",
    nickname: "Pri",
    username: "priya",
    email: "priya.rao@example.com",
    level: "advanced",
    xp: 8420,
    lessonsAvgGrade: 96,
    dob: "1992-07-25",
    joinDate: "2014-08-10",
    followers: 220,
    following: 95,
    dailyStreak: 29,
    weeklyThis: [1, 0, 3, 6, 4, 8, 0],
    weeklyLast: [5, 2, 0, 1, 3, 2, 0],
    avatarSrc: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: "user4",
    firstName: "Marcus",
    lastName: "Olsen",
    nickname: "Mark",
    username: "marc_olsen",
    email: "marcus.olsen@example.com",
    level: "beginner",
    xp: 890,
    lessonsAvgGrade: 79,
    dob: "2001-06-11",
    joinDate: "2020-03-19",
    followers: 8,
    following: 4,
    dailyStreak: 3,
    weeklyThis: [2, 0, 1, 0, 1, 2, 1],
    weeklyLast: [3, 2, 0, 0, 0, 2, 0],
    avatarSrc: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: "user5",
    firstName: "Aisha",
    lastName: "Khan",
    nickname: "Aish",
    username: "aishak",
    email: "aisha.khan@example.com",
    level: "intermediate",
    xp: 4200,
    lessonsAvgGrade: 90,
    dob: "1998-09-08",
    joinDate: "2016-11-23",
    followers: 33,
    following: 28,
    dailyStreak: 10,
    weeklyThis: [5, 6, 3, 8, 2, 4, 1],
    weeklyLast: [7, 3, 5, 2, 1, 2, 3],
    avatarSrc: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: "user6",
    firstName: "Noah",
    lastName: "Carter",
    nickname: "Noah",
    username: "noahc",
    email: "noah.carter@example.com",
    level: "advanced",
    xp: 10210,
    lessonsAvgGrade: 94,
    dob: "1990-12-19",
    joinDate: "2012-06-09",
    followers: 185,
    following: 122,
    dailyStreak: 46,
    weeklyThis: [4, 2, 3, 7, 6, 5, 0],
    weeklyLast: [3, 3, 2, 6, 4, 4, 2],
    avatarSrc: "https://i.pravatar.cc/150?img=24",
  },
  {
    id: "user7",
    firstName: "Yuki",
    lastName: "Tanaka",
    nickname: "Yuki",
    username: "tanakay",
    email: "yuki.tanaka@example.com",
    level: "beginner",
    xp: 1570,
    lessonsAvgGrade: 84,
    dob: "2003-04-04",
    joinDate: "2022-02-15",
    followers: 6,
    following: 11,
    dailyStreak: 6,
    weeklyThis: [2, 4, 2, 3, 1, 3, 0],
    weeklyLast: [4, 3, 1, 0, 2, 2, 0],
    avatarSrc: "https://i.pravatar.cc/150?img=35",
  },
  {
    id: "user8",
    firstName: "Theo",
    lastName: "Martinez",
    nickname: "Theo",
    username: "theom",
    email: "theo.martinez@example.com",
    level: "intermediate",
    xp: 3375,
    lessonsAvgGrade: 91,
    dob: "1997-08-23",
    joinDate: "2017-03-10",
    followers: 52,
    following: 47,
    dailyStreak: 11,
    weeklyThis: [3, 2, 5, 6, 2, 4, 1],
    weeklyLast: [5, 3, 2, 3, 2, 5, 1],
    avatarSrc: "https://i.pravatar.cc/150?img=41",
  },
  {
    id: "user9",
    firstName: "Isabella",
    lastName: "Wong",
    nickname: "Izzy",
    username: "izwong",
    email: "isabella.wong@example.com",
    level: "advanced",
    xp: 9320,
    lessonsAvgGrade: 95,
    dob: "1994-05-14",
    joinDate: "2013-09-02",
    followers: 202,
    following: 118,
    dailyStreak: 23,
    weeklyThis: [2, 5, 3, 7, 4, 6, 1],
    weeklyLast: [4, 4, 5, 6, 3, 5, 2],
    avatarSrc: "https://i.pravatar.cc/150?img=49",
  },
  {
    id: "user10",
    firstName: "Ethan",
    lastName: "Brooks",
    nickname: "Ethan",
    username: "ethbrooks",
    email: "ethan.brooks@example.com",
    level: "intermediate",
    xp: 2765,
    lessonsAvgGrade: 86,
    dob: "1996-10-30",
    joinDate: "2017-01-09",
    followers: 26,
    following: 17,
    dailyStreak: 9,
    weeklyThis: [1, 0, 3, 2, 4, 3, 0],
    weeklyLast: [2, 2, 3, 1, 3, 1, 0],
    avatarSrc: "https://i.pravatar.cc/150?img=58",
  },
];
export const weekdayLabels = ["Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu"];
